import os
import json
import csv
from datetime import datetime

class DriftReportBuilder:
    """
    Constructs model drift reports in JSON, Markdown, and CSV, and archives snapshots.
    """
    @staticmethod
    def get_drift_dir() -> str:
        curr = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        path = os.path.join(curr, "reports", "drift")
        os.makedirs(path, exist_ok=True)
        return path

    @classmethod
    def save_drift_reports(cls, drift_data: dict, baseline_version: str, target_version: str):
        drift_dir = cls.get_drift_dir()
        timestamp_str = datetime.utcnow().isoformat() + "Z"
        date_folder = datetime.utcnow().strftime("%Y-%m-%d")
        
        report_meta = {
            "report_version": "1.0",
            "generated_at": timestamp_str,
            "generated_by": "DriftReportBuilder",
            "project_version": "1.0",
            "baseline_dataset_version": baseline_version,
            "target_dataset_version": target_version,
            "drift_percentage": drift_data["drift_percentage"],
            "drift_severity": drift_data["drift_severity"],
            "suggest_retraining": drift_data["suggest_retraining"]
        }

        full_report = {
            "metadata": report_meta,
            "results": drift_data
        }

        # Save main JSON report
        json_path = os.path.join(drift_dir, "drift_report.json")
        with open(json_path, 'w') as f:
            json.dump(full_report, f, indent=4)

        # Save historical snapshots
        history_dir = os.path.join(drift_dir, "history", date_folder)
        os.makedirs(history_dir, exist_ok=True)
        with open(os.path.join(history_dir, "drift_report.json"), 'w') as f:
            json.dump(full_report, f, indent=4)

        # Update drift_history.json list
        history_path = os.path.join(drift_dir, "drift_history.json")
        history_list = []
        if os.path.exists(history_path):
            try:
                with open(history_path, 'r') as f:
                    history_list = json.load(f)
            except Exception:
                history_list = []
        history_list.append(full_report)
        with open(history_path, 'w') as f:
            json.dump(history_list, f, indent=4)

        # Save drift_summary.md
        md_path = os.path.join(drift_dir, "drift_summary.md")
        changed_features = [f for f, res in drift_data["features_drift"].items() if res["drift_detected"]]
        
        changed_features_str = "\n".join(f"- {f} (shift: {drift_data['features_drift'][f]['mean_shift']} std dev)" for f in changed_features)
        
        md_content = f"""# EDQI Model Drift Monitoring Summary Report

**Metadata Header**
- **Project:** Enterprise AI Decision Intelligence Platform
- **Module:** Enterprise Data Quality Intelligence
- **Version:** 1.0
- **Generated:** {date_folder}
- **Generated By:** DriftReportBuilder
- **Baseline Dataset Version:** `{baseline_version}`
- **Target Dataset Version:** `{target_version}`
- **Report Version:** 1.0

---

## Executive Summary
- **Overall Drift Ratio:** `{drift_data["drift_percentage"]}%`
- **Drift Severity:** `{drift_data["drift_severity"]}`
- **Retraining Suggested:** `{drift_data["suggest_retraining"]}`
- **Baseline Size:** `{drift_data["dataset_sizes"]["baseline"]}`
- **Target Size:** `{drift_data["dataset_sizes"]["target"]}`

## Changed Features ({len(changed_features)})
{changed_features_str if changed_features else "- No feature drift detected."}
"""
        with open(md_path, 'w') as f:
            f.write(md_content)
            
        with open(os.path.join(history_dir, "drift_summary.md"), 'w') as f:
            f.write(md_content)

        # Save drift_statistics.csv
        csv_path = os.path.join(drift_dir, "drift_statistics.csv")
        cls._write_csv(csv_path, drift_data["features_drift"])
        cls._write_csv(os.path.join(history_dir, "drift_statistics.csv"), drift_data["features_drift"])

    @staticmethod
    def _write_csv(path: str, features_drift: dict):
        with open(path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["Feature", "Mean Baseline", "Mean Target", "Mean Shift", "Std Baseline", "Std Target", "Drift Detected"])
            for feat, res in features_drift.items():
                writer.writerow([
                    feat,
                    res["mean_baseline"],
                    res["mean_target"],
                    res["mean_shift"],
                    res["std_baseline"],
                    res["std_target"],
                    res["drift_detected"]
                ])
