# Generated by Django 5.2.17 on 2026-08-21 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Direct text answer or query.')),
                ('intent_category', models.CharField(blank=True, default='SEMANTIC_UNSTRUCTURED', max_length=50)),
                ('retrieval_method', models.CharField(blank=True, default='HYBRID', max_length=50)),
                ('evidence_chunks', models.JSONField(blank=True, default=list, help_text='Level 2 Evidence Chunks')),
                ('knowledge_paths', models.JSONField(blank=True, default=list, help_text='Level 3 KG Traversal Paths')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Level 4 Source Provenance')),
                ('model_used', models.CharField(default='Phi-3.5-Mini-3.8B-Q4_K_M', max_length=50)),
                ('latency_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge_assistant.assistantsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
