# Generated by Django 5.2.17 on 2026-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='kg_path',
            field=models.JSONField(blank=True, default=list, help_text='Active Reasoning KG Path', null=True),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='response_levels',
            field=models.JSONField(blank=True, default=dict, help_text='4-Level Progressive Response Levels', null=True),
        ),
    ]
