# Generated by Django 5.2.17 on 2026-09-04 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_assistant', '0002_assistantmessage_kg_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitivePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_scope', models.CharField(blank=True, help_text='Target document or dataset title', max_length=255, null=True)),
                ('pattern_type', models.CharField(choices=[('RECURRING_PATTERN', 'Recurring Pattern'), ('TREND', 'Trend'), ('CHANGE', 'Change'), ('ANOMALY', 'Anomaly'), ('CORRELATION', 'Correlation'), ('RELATIONSHIP_PATTERN', 'Relationship Pattern'), ('BEHAVIORAL_PATTERN', 'Behavioral Pattern'), ('TEMPORAL_PATTERN', 'Temporal Pattern')], default='RECURRING_PATTERN', max_length=50)),
                ('knowledge_level', models.CharField(choices=[('DIRECT_FACT', 'Direct Fact'), ('DETERMINISTIC_CALCULATION', 'Deterministic Calculation'), ('DERIVED_INTERPRETATION', 'Derived Interpretation'), ('OBSERVED_PATTERN', 'Observed Pattern'), ('TREND', 'Trend'), ('ANOMALY', 'Anomaly'), ('CORRELATION', 'Correlation'), ('HYPOTHESIS', 'Hypothesis')], default='OBSERVED_PATTERN', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Pattern'), ('WEAKENED', 'Weakened Pattern'), ('CHANGED', 'Changed Pattern'), ('INVALIDATED', 'Invalidated Pattern')], default='ACTIVE', max_length=30)),
                ('confidence', models.CharField(default='90.0%', max_length=20)),
                ('observation_count', models.IntegerField(default=1)),
                ('time_range', models.CharField(blank=True, default='Current Period', max_length=100)),
                ('first_observed', models.DateTimeField(auto_now_add=True)),
                ('last_observed', models.DateTimeField(auto_now=True)),
                ('supporting_evidence_ids', models.JSONField(blank=True, default=list)),
                ('supporting_sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(help_text='Enforces strict authorization scope per user/role.', on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_observed'],
            },
        ),
    ]
