# Generated by Django 6.0.6 on 2026-07-28 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('status', models.CharField(default='active', help_text='State of the record (e.g., active, processed, completed, failed).', max_length=50)),
                ('file', models.FileField(help_text='Path to the stored file inside the Uploads directory.', upload_to='')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the file contents to enforce deduplication.', max_length=64, unique=True)),
                ('original_name', models.CharField(help_text='The original filename before upload storage saving.', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='The physical file size in bytes.')),
                ('mime_type', models.CharField(help_text='The verified MIME content-type of the file.', max_length=100)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Parsing processing status of this document.', max_length=20)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('clean', 'Clean'), ('duplicate', 'Duplicate'), ('incomplete', 'Incomplete'), ('invalid', 'Invalid'), ('suspicious', 'Suspicious')], default='pending', help_text='Data Quality validation state classified by EDQI.', max_length=20)),
                ('uploaded_by', models.ForeignKey(help_text='The system user who uploaded this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
