# Generated by Django 6.0.6 on 2026-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Parsed/extracted structural header metadata.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='parser_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'EXCEL'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('API', 'API')], default='TEXT', help_text='The classification type indicating which parsing strategy to execute.', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='standardized_record',
            field=models.JSONField(blank=True, help_text='Standardized enterprise schema mapping dictionary.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Path to the stored file inside the Uploads/raw/ directory.', upload_to='raw/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('PARSING', 'Parsing'), ('OCR_RUNNING', 'OCR Running'), ('STANDARDIZED', 'Standardized'), ('FAILED', 'Failed')], default='UPLOADED', help_text='Parsing processing status of this document.', max_length=20),
        ),
    ]
