# Generated by Django 6.0.6 on 2026-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_document_metadata_document_parser_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='Average word-level confidence percentage returned by the OCR Engine.', null=True),
        ),
    ]
