# Generated by Django 6.0.6 on 2026-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_document_ocr_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_metadata',
            field=models.JSONField(blank=True, help_text='Persistent OCR execution metadata including confidence metrics and timestamps.', null=True),
        ),
    ]
