# Generated by Django 6.0.6 on 2026-07-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_document_ocr_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(help_text='Unique pipeline execution correlation identifier.', max_length=50)),
                ('stage_name', models.CharField(help_text='Name of the execution stage.', max_length=50)),
                ('stage_status', models.CharField(help_text='Completion status of the stage (e.g. SUCCESS, FAILED, SKIPPED).', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Execution start timestamp of this stage.')),
                ('end_time', models.DateTimeField(help_text='Execution end timestamp of this stage.')),
                ('execution_duration', models.FloatField(help_text='Execution time in seconds.')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retries attempted.')),
                ('warning_count', models.IntegerField(default=0, help_text='Number of warnings compiled.')),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors compiled.')),
                ('document', models.ForeignKey(help_text='The target document processed in this pipeline run.', on_delete=django.db.models.deletion.CASCADE, related_name='processing_histories', to='ingestion.document')),
            ],
        ),
    ]
