# Generated by Django 5.2.17 on 2026-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_processinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='parser_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'EXCEL'), ('CSV', 'CSV'), ('JSON', 'JSON'), ('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('API', 'API'), ('DOCX', 'DOCX')], default='TEXT', help_text='The classification type indicating which parsing strategy to execute.', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Unique Gmail Message-ID header or IMAP UID identifier.', max_length=255, unique=True)),
                ('sender', models.CharField(help_text='Sender email address.', max_length=255)),
                ('recipient', models.CharField(help_text='Recipient enterprise mailbox address.', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Email subject line.', max_length=500)),
                ('received_at', models.DateTimeField(blank=True, help_text='Email received timestamp.', null=True)),
                ('body', models.TextField(blank=True, help_text='Extracted email body content.')),
                ('has_attachments', models.BooleanField(default=False, help_text='Flag indicating if the email contained file attachments.')),
                ('attachment_count', models.IntegerField(default=0, help_text='Number of file attachments extracted from the email.')),
                ('attachment_names', models.JSONField(blank=True, default=list, help_text='List of attachment filenames extracted.')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the email was processed by the Celery worker.')),
                ('status', models.CharField(default='SUCCESS', help_text='Processing status (SUCCESS, FAILED, DUPLICATE_SKIPPED).', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email processing encountered an exception.', null=True)),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents created and ingested from this email message (body or attachments).', related_name='source_emails', to='ingestion.document')),
            ],
        ),
    ]
