import os
import json
import csv
from datetime import datetime

class EvolutionReportBuilder:
    """
    Tracks and documents modifications, record sizes, and hashes of datasets over time.
    """
    @staticmethod
    def get_datasets_dir() -> str:
        curr = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        path = os.path.join(curr, "reports", "datasets")
        os.makedirs(path, exist_ok=True)
        return path

    @classmethod
    def record_dataset_evolution(cls, dataset_version: str, record_count: int, feature_count: int, dataset_hash: str, dataset_size_mb: float, created_by: str = "System"):
        datasets_dir = cls.get_datasets_dir()
        date_folder = datetime.utcnow().strftime("%Y-%m-%d")
        timestamp_str = datetime.utcnow().isoformat() + "Z"

        new_record = {
            "dataset_version": dataset_version,
            "dataset_hash": dataset_hash,
            "dataset_size_mb": round(dataset_size_mb, 4),
            "created_date": timestamp_str,
            "created_by": created_by,
            "source": "KnowledgeDocument Registry",
            "record_count": record_count,
            "feature_count": feature_count,
            "target_count": {
                "Excellent": 0,
                "Good": 0,
                "Average": 0,
                "Poor": 0
            }
        }

        # 1. Update Dataset_Version_History.json
        history_path = os.path.join(datasets_dir, "Dataset_Version_History.json")
        history = []
        if os.path.exists(history_path):
            try:
                with open(history_path, 'r') as f:
                    history = json.load(f)
            except Exception:
                history = []
        history.append(new_record)
        with open(history_path, 'w') as f:
            json.dump(history, f, indent=4)

        # Archive historical snapshot folder
        history_dir = os.path.join(datasets_dir, "history", date_folder)
        os.makedirs(history_dir, exist_ok=True)
        with open(os.path.join(history_dir, "Dataset_Version_History.json"), 'w') as f:
            json.dump(history, f, indent=4)

        # 2. Write Dataset_Version_History.md
        md_path = os.path.join(datasets_dir, "Dataset_Version_History.md")
        md_rows = []
        for h in history:
            md_rows.append(
                f"| {h['dataset_version']} | {h['record_count']} | {h['feature_count']} | {h['dataset_size_mb']} MB | {h['dataset_hash'][:16]}... | {h['created_by']} | {h['created_date']} |"
            )
        
        md_content = f"""# Enterprise Dataset Evolution History Report

**Metadata Header**
- **Project:** Enterprise AI Decision Intelligence Platform
- **Module:** Enterprise Data Quality Intelligence
- **Version:** 1.0
- **Generated:** {date_folder}
- **Generated By:** EvolutionReportBuilder
- **Report Version:** 1.0

---

## Dataset Evolution Chain

| Version | Records | Features | Size | SHA-256 | Created By | Created Date |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
{"\n".join(md_rows) if md_rows else "| - | - | - | - | - | - | - |"}
"""
        with open(md_path, 'w') as f:
            f.write(md_content)
        with open(os.path.join(history_dir, "Dataset_Version_History.md"), 'w') as f:
            f.write(md_content)

        # 3. Write Dataset_Version_History.csv
        csv_path = os.path.join(datasets_dir, "Dataset_Version_History.csv")
        cls._write_csv(csv_path, history)
        cls._write_csv(os.path.join(history_dir, "Dataset_Version_History.csv"), history)

    @staticmethod
    def _write_csv(path: str, history: list):
        with open(path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["Dataset Version", "Dataset Hash", "Dataset Size (MB)", "Created Date", "Created By", "Source", "Record Count", "Feature Count"])
            for h in history:
                writer.writerow([
                    h["dataset_version"],
                    h["dataset_hash"],
                    h["dataset_size_mb"],
                    h["created_date"],
                    h["created_by"],
                    h["source"],
                    h["record_count"],
                    h["feature_count"]
                ])
