# Generated by Django 6.0.6 on 2026-08-04 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseDataQualityReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('overall_quality_score', models.FloatField()),
                ('previous_quality_score', models.FloatField(default=0.0)),
                ('trend', models.CharField(default='STABLE', max_length=20)),
                ('completeness_score', models.FloatField()),
                ('validity_score', models.FloatField()),
                ('consistency_score', models.FloatField()),
                ('uniqueness_score', models.FloatField()),
                ('timeliness_score', models.FloatField()),
                ('quality_grade', models.CharField(max_length=5)),
                ('assessment_status', models.CharField(default='PENDING', max_length=50)),
                ('assessment_engine_version', models.CharField(default='1.0', max_length=20)),
                ('rules_version', models.CharField(default='1.0', max_length=20)),
                ('feature_version', models.CharField(default='1.0', max_length=20)),
                ('quality_features', models.JSONField(blank=True, default=dict)),
                ('ml_ready_features', models.JSONField(blank=True, default=dict)),
                ('processing_trace', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='repository.knowledgerecord')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseDatasetProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('document_statistics', models.JSONField(blank=True, default=dict)),
                ('field_profiles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_profiles', to='repository.knowledgedocument')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseQualityMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metrics_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('batch_id', models.CharField(max_length=255)),
                ('record_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('median_score', models.FloatField(default=0.0)),
                ('min_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('standard_deviation', models.FloatField(default=0.0)),
                ('grade_distribution', models.JSONField(blank=True, default=dict)),
                ('issue_distribution', models.JSONField(blank=True, default=dict)),
                ('execution_statistics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='repository.knowledgedocument')),
            ],
        ),
        migrations.CreateModel(
            name='QualityIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('field_name', models.CharField(max_length=255)),
                ('issue_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='MEDIUM', max_length=50)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('recommendation_confidence', models.FloatField(default=1.0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='edqi.enterprisedataqualityreport')),
            ],
        ),
    ]
