# Generated by Django 6.0.6 on 2026-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisequalitymetrics',
            name='average_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enterprisequalitymetrics',
            name='dataset_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='enterprisequalitymetrics',
            name='excellent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enterprisequalitymetrics',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enterprisequalitymetrics',
            name='poor_count',
            field=models.IntegerField(default=0),
        ),
    ]
