# Generated by Django 6.0.6 on 2026-08-04 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqi', '0002_enterprisequalitymetrics_average_count_and_more'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('algorithm', models.CharField(max_length=100)),
                ('dataset_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('VALIDATING', 'Validating'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], default='TRAINING', max_length=30)),
                ('model_health', models.CharField(choices=[('HEALTHY', 'Healthy'), ('NEEDS_RETRAINING', 'Needs Retraining'), ('DEPRECATED', 'Deprecated')], default='HEALTHY', max_length=30)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('roc_auc', models.FloatField(default=0.0)),
                ('cross_validation_score', models.FloatField(default=0.0)),
                ('training_time_sec', models.FloatField(default=0.0)),
                ('prediction_time_sec', models.FloatField(default=0.0)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_prediction_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_count', models.IntegerField(default=0)),
                ('random_seed', models.IntegerField(default=42)),
                ('training_dataset_size', models.IntegerField(default=0)),
                ('testing_dataset_size', models.IntegerField(default=0)),
                ('feature_count', models.IntegerField(default=0)),
                ('training_configuration', models.JSONField(blank=True, default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('model_path', models.CharField(max_length=500)),
                ('pipeline_path', models.CharField(max_length=500)),
                ('supports_explainability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prediction_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('predicted_grade', models.CharField(max_length=20)),
                ('predicted_probability', models.JSONField(blank=True, default=dict)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('dataset_version', models.CharField(max_length=50)),
                ('feature_version', models.CharField(default='1.0', max_length=50)),
                ('prediction_time_ms', models.FloatField(default=0.0)),
                ('confidence_level', models.CharField(choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=30)),
                ('execution_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='repository.knowledgerecord')),
            ],
        ),
    ]
