# Generated by Django 6.0.6 on 2026-08-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqi', '0003_trainedmodel_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='actual_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='feature_schema_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='input_feature_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='pipeline_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='prediction_source',
            field=models.CharField(default='Rule Engine', max_length=50),
        ),
    ]
