# Generated by Django 6.0.6 on 2026-08-05 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqi', '0004_predictionhistory_actual_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainabilityReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_prediction', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('base_value', models.FloatField(default=0.0)),
                ('predicted_probability', models.JSONField(blank=True, default=dict)),
                ('top_positive_features', models.JSONField(blank=True, default=list)),
                ('top_negative_features', models.JSONField(blank=True, default=list)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('raw_shap_values', models.JSONField(blank=True, default=dict)),
                ('normalized_shap_values', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('explainer_name', models.CharField(max_length=100)),
                ('explainer_version', models.CharField(default='1.0', max_length=50)),
                ('model_algorithm', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=100)),
                ('dataset_version', models.CharField(max_length=50)),
                ('feature_version', models.CharField(default='1.0', max_length=50)),
                ('processing_trace', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explainability_reports', to='edqi.predictionhistory')),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explainability_reports', to='edqi.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('priority_score', models.FloatField(default=0.0)),
                ('recommendation', models.TextField()),
                ('expected_improvement', models.FloatField(default=0.0)),
                ('recommendation_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_records', to='edqi.explainabilityreport')),
            ],
        ),
    ]
