# Generated by Django 6.0.6 on 2026-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edqi', '0005_explainabilityreport_recommendationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisedatasetprofile',
            name='ingestion_batch_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprisedatasetprofile',
            name='source_name',
            field=models.CharField(default='Local Ingestion', max_length=200),
        ),
        migrations.AddField(
            model_name='enterprisedatasetprofile',
            name='source_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enterprisedatasetprofile',
            name='source_type',
            field=models.CharField(default='File', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='actual_improvement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='after_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='before_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='difference',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='execution_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommendation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommendation_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='next_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='parent_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
