import os
import csv
from datetime import datetime

class HealthReportBuilder:
    """
    Formats history health score trends to MD and CSV datasets.
    """
    @classmethod
    def build_reports(cls, health_dir: str, history_list: list):
        date_folder = datetime.utcnow().strftime("%Y-%m-%d")
        history_dir = os.path.join(health_dir, "history", date_folder)
        os.makedirs(history_dir, exist_ok=True)

        # Write health_history.md
        md_path = os.path.join(health_dir, "health_history.md")
        md_rows = []
        for h in history_list:
            md_rows.append(
                f"| {h['timestamp']} | {h['health_score']}% | {h['health_grade']} | {h['risk_level']} | {h['trend']} |"
            )
        
        rows_str = "\n".join(md_rows) if md_rows else "| - | - | - | - | - |"
        md_content = f"""# Enterprise Platform Quality Health History Report

**Metadata Header**
- **Project:** Enterprise AI Decision Intelligence Platform
- **Module:** Enterprise Data Quality Intelligence
- **Version:** 1.0
- **Generated:** {date_folder}
- **Generated By:** HealthReportBuilder
- **Report Version:** 1.0

---

## Health Trends Log

| Timestamp | Health Score (%) | Grade | Risk Level | Trend |
| :--- | :--- | :--- | :--- | :--- |
{rows_str}
"""
        with open(md_path, 'w') as f:
            f.write(md_content)
        with open(os.path.join(history_dir, "health_history.md"), 'w') as f:
            f.write(md_content)

        # Write health_history.csv
        csv_path = os.path.join(health_dir, "health_history.csv")
        cls._write_csv(csv_path, history_list)
        cls._write_csv(os.path.join(history_dir, "health_history.csv"), history_list)

    @staticmethod
    def _write_csv(path: str, history_list: list):
        with open(path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["Timestamp", "Health Score (%)", "Grade", "Risk Level", "Trend"])
            for h in history_list:
                writer.writerow([
                    h["timestamp"],
                    h["health_score"],
                    h["health_grade"],
                    h["risk_level"],
                    h["trend"]
                ])
