# Generated by Django 5.2.16 on 2026-07-31 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0005_processinghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('current_version', models.IntegerField(default=1)),
                ('repository_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('CONFLICT', 'Conflict'), ('PROCESSING', 'Processing')], default='ACTIVE', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_content', models.TextField(blank=True, default='')),
                ('record_count', models.IntegerField(default=0)),
                ('version_count', models.IntegerField(default=1)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('repository_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, help_text='References the original Phase 1 uploaded document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='ingestion.document')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('raw_content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('change_summary', models.JSONField(blank=True, default=dict)),
                ('source_document_id', models.IntegerField(blank=True, null=True)),
                ('reason_for_update', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='repository.knowledgedocument')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_version_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('canonical_data', models.JSONField(blank=True, default=dict)),
                ('additional_fields', models.JSONField(blank=True, default=dict)),
                ('embedding_status', models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='NOT_GENERATED', max_length=50)),
                ('embedding_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='repository.knowledgedocument')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='repository.knowledgedocument')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='repository.knowledgedocument')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryAuditEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SYNC', 'Sync'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('ARCHIVE', 'Archive')], max_length=50)),
                ('user', models.CharField(help_text='Username of the operator.', max_length=150)),
                ('reason', models.TextField(blank=True, default='')),
                ('pipeline_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('knowledge_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='repository.knowledgedocument')),
            ],
            options={
                'verbose_name_plural': 'Repository audit entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
