# Generated by Django 5.2.17 on 2026-09-09 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='logical_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_knowledge_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RepositoryFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('repository_type', models.CharField(choices=[('team', 'Team Repository'), ('personal', 'Personal Repository')], default='team', max_length=20)),
                ('logical_path', models.CharField(db_index=True, max_length=1000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repository_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='repository.repositoryfolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('repository_type', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='References the logical folder containing this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='repository.repositoryfolder'),
        ),
    ]
