import uuid
from django.db import models

class ExplainabilityReport(models.Model):
    """
    Stores local and global feature attribution explanation reports generated by SHAP/Fallback explainer.
    """
    report_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    prediction = models.ForeignKey(
        'edqi.PredictionHistory',
        on_delete=models.CASCADE,
        related_name='explainability_reports'
    )
    trained_model = models.ForeignKey(
        'edqi.TrainedModel',
        on_delete=models.CASCADE,
        related_name='explainability_reports'
    )
    
    overall_prediction = models.CharField(max_length=50) # e.g. Excellent, Good, Average, Poor
    confidence_score = models.FloatField(default=0.0)
    base_value = models.FloatField(default=0.0)
    predicted_probability = models.JSONField(default=dict, blank=True)
    
    # Feature attributions lists
    top_positive_features = models.JSONField(default=list, blank=True) # [{"feature": "...", "val": 0.23, "pct": 45}]
    top_negative_features = models.JSONField(default=list, blank=True)
    feature_importance = models.JSONField(default=dict, blank=True)
    
    # SHAP values
    raw_shap_values = models.JSONField(default=dict, blank=True)
    normalized_shap_values = models.JSONField(default=dict, blank=True)
    
    recommendations = models.JSONField(default=list, blank=True)
    summary = models.TextField(blank=True, null=True)
    
    # Explainer & Model tracing tags
    explainer_name = models.CharField(max_length=100) # e.g. SHAP TreeExplainer, Fallback Explainer
    explainer_version = models.CharField(max_length=50, default='1.0')
    model_algorithm = models.CharField(max_length=100)
    model_version = models.CharField(max_length=100)
    dataset_version = models.CharField(max_length=50)
    feature_version = models.CharField(max_length=50, default='1.0')
    
    processing_trace = models.JSONField(default=dict, blank=True) # prediction_time, explanation_time, fallback_used...
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Report {self.report_id} (Pred: {self.overall_prediction} - Conf: {self.confidence_score})"


class RecommendationHistory(models.Model):
    """
    Stores historical logs of actionable quality recommendations generated.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('REVIEWED', 'Reviewed'),
        ('ACCEPTED', 'Accepted'),
        ('REJECTED', 'Rejected'),
        ('IMPLEMENTED', 'Implemented')
    ]

    recommendation_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    report = models.ForeignKey(
        ExplainabilityReport,
        on_delete=models.CASCADE,
        related_name='recommendation_records'
    )
    recommendation_type = models.CharField(max_length=100) # e.g. MISSING_REQUIRED_FIELD
    category = models.CharField(max_length=100) # Completeness, Validity, Consistency, Uniqueness, Timeliness
    priority = models.CharField(max_length=20) # HIGH, MEDIUM, LOW
    priority_score = models.FloatField(default=0.0) # 0-100 score
    
    recommendation = models.TextField()
    expected_improvement = models.FloatField(default=0.0) # e.g. +12.0 (%)
    recommendation_confidence = models.FloatField(default=0.0) # e.g. 95.0 (%)
    
    # Effectiveness metrics
    before_score = models.FloatField(default=0.0)
    after_score = models.FloatField(default=0.0)
    actual_improvement = models.FloatField(default=0.0)
    difference = models.FloatField(default=0.0)
    recommendation_accepted = models.BooleanField(default=False)
    recommendation_applied = models.BooleanField(default=False)
    execution_timestamp = models.DateTimeField(null=True, blank=True)
    
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default='PENDING')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Recommendation {self.recommendation_id} -> {self.category} ({self.priority})"
