# Generated by Django 6.0.6 on 2026-08-03 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCandidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('candidate_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_segment_id', models.CharField(help_text='Unique segment identifier in source context.', max_length=100)),
                ('target_segment_id', models.CharField(help_text='Unique segment identifier in target context.', max_length=100)),
                ('source_text', models.TextField(help_text='Text content of the source segment.')),
                ('target_text', models.TextField(help_text='Text content of the target segment.')),
                ('source_page', models.IntegerField(blank=True, help_text='Page number in source document.', null=True)),
                ('target_page', models.IntegerField(blank=True, help_text='Page number in target document.', null=True)),
                ('source_section', models.CharField(blank=True, help_text='Section heading in source.', max_length=255, null=True)),
                ('target_section', models.CharField(blank=True, help_text='Section heading in target.', max_length=255, null=True)),
                ('strategy_used', models.CharField(help_text='Strategy strategy name used to generate this pair.', max_length=100)),
                ('strategy_confidence', models.FloatField(help_text='Configured confidence score for the strategy matching.')),
                ('entity_type', models.CharField(blank=True, default='', help_text='Record entity category type (if applicable).', max_length=100)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='GENERATED', help_text='Processing state status of this candidate.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dynamic matching metadata attributes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(help_text='Reference to the source KnowledgeDocument.', on_delete=django.db.models.deletion.CASCADE, related_name='source_candidates', to='repository.knowledgedocument')),
                ('target_document', models.ForeignKey(help_text='Reference to the comparison target KnowledgeDocument.', on_delete=django.db.models.deletion.CASCADE, related_name='target_candidates', to='repository.knowledgedocument')),
            ],
        ),
    ]
