# Generated by Django 6.0.6 on 2026-08-03 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_conflict', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeConflict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conflict_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('conflict_type', models.CharField(choices=[('CONSISTENT', 'Consistent'), ('DUPLICATE', 'Duplicate'), ('CONFLICTING', 'Conflicting'), ('OUTDATED', 'Outdated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=50)),
                ('overall_similarity', models.FloatField(help_text='The primary decision similarity score.')),
                ('similarity_metrics', models.JSONField(blank=True, default=dict, help_text='Carries cosine, length, and keyword similarity parameters.')),
                ('confidence_score', models.FloatField()),
                ('embedding_model', models.CharField(max_length=100)),
                ('embedding_metadata', models.JSONField(blank=True, default=dict, help_text='Dimensions and parameters.')),
                ('classifier_used', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Specific overlapping fields or mismatch indicators.')),
                ('processing_trace', models.JSONField(default=dict, help_text='System-level execution details for auditing.')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('REVIEW_PENDING', 'Review Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NEW', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_candidate', models.ForeignKey(help_text='Reference to the comparison candidate pair.', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='knowledge_conflict.knowledgecandidate')),
                ('source_document', models.ForeignKey(help_text='Reference to the source KnowledgeDocument.', on_delete=django.db.models.deletion.CASCADE, related_name='source_conflicts', to='repository.knowledgedocument')),
                ('target_document', models.ForeignKey(help_text='Reference to the target KnowledgeDocument.', on_delete=django.db.models.deletion.CASCADE, related_name='target_conflicts', to='repository.knowledgedocument')),
            ],
        ),
    ]
