# Generated by Django 6.0.6 on 2026-08-03 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_conflict', '0002_knowledgeconflict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictAuditHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('REVIEW_STARTED', 'Review Started'), ('DECISION_CONFIRMED', 'Decision Confirmed'), ('MERGED', 'Merged'), ('MANUAL_EDIT', 'Manual Edit'), ('IGNORE', 'Ignore'), ('ARCHIVED', 'Archived')], default='REVIEW_STARTED', max_length=50)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to='knowledge_conflict.knowledgeconflict')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConflictReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=50)),
                ('decision', models.CharField(blank=True, choices=[('CONFIRMED', 'Confirmed Conflict'), ('FALSE_POSITIVE', 'False Positive'), ('NEEDS_MORE_REVIEW', 'Needs More Review')], max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('KEEP_SOURCE', 'Keep Source Document'), ('KEEP_TARGET', 'Keep Target Document'), ('MERGE', 'Merge Records'), ('MANUAL_EDIT', 'Manual Edit'), ('IGNORE', 'Ignore False Positive')], max_length=50, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict', models.ForeignKey(help_text='Reference to the analyzed knowledge conflict.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='knowledge_conflict.knowledgeconflict')),
                ('reviewer', models.ForeignKey(help_text='Analyst user reviewing this conflict.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
